import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "./base/Header";
import Footer from "./base/Footer";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          
            <Header/>
              <div
  style={{
    display: "flex",
    justifyContent: "center", 
    alignItems: "center",     
    backgroundColor: "#444444",
    paddingTop: "60px",
    paddingBottom: "60px",
    minHeight: "100vh",
  }}
>
  <div style={{ width: "60vw" }}>
    <AntdRegistry>{children}</AntdRegistry>
  </div>
</div>
             <Footer/>
          
         
          
          
      </body>
    </html>
  );
}
